name: External Actions Reference Example

on:
  schedule:
    - cron: "0/2 * * * *"
    - cron: "0/3 * * * *"
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
        # This is the checkout official action for checing out the code we are at
      - name: Checkout code from Github
        uses: actions/checkout@v2
        # List files after checkout
      - name: List files
        run: |
          pwd
          ls -la
      - name: Simple JS Action
        id: greet
        # see https://github.com/actions/hello-world-javascript-action
        uses: actions/hello-world-javascript-action@v1 # This is a public published action, but we can also use our own
        with:
          who-to-greet: John # This is an input parameter the action can recive
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}" # This reference the output of the step before